### ISSUE TITLE
Date of borth format

### ISSUE THREAD

**Issue by mohamoha6200** [lakshydeep-14/DOB-Input-Field#1]
Hello and thank you for the package !
How come the package doesnt support a flag for different dob formats ? I can see that it only supports mm/dd/yyyy !
What to do if I wanted to have a different format such as dd/mm/yyyy ?
thanks you

**Comment by lakshydeep-14** [comment]
Will update it for sure.
Thanks for using this package.
Update will come in a week.

Do follow on medium, linkedin, YouTube and on GitHub as well.

https://www.linkedin.com/in/lakshydeep-14/


https://lakshydeep-14.medium.com/


https://www.youtube.com/channel/UCsBeBQvSw-EIla1i4YqqfAg

Thanks & Regards
Lakshydeep Vikram

**Comment by lakshydeep-14** [comment]
https://pub.dev/packages/dob_input_field
please check. I had added this feature. have a look once.

Thanks
Lakshydeep Vikram

**Comment by mohamoha6200** [comment]
Thank you the feature added conforms to the desired one, although I noticed that my hinText has been overridden by the format, could you make sure that the format hintText is just a fallback ?

**Comment by lakshydeep-14** [comment]
I will check it.
